# Generated by Django 3.2.9 on 2021-11-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_rename_approval_approvals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='approvals',
            new_name='PatientInformation',
        ),
    ]
